# Generated by Django 4.2.6 on 2023-12-12 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_blog_posted_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['-posted'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ['-posted'], 'verbose_name': 'Корзина', 'verbose_name_plural': 'Товары Корзины'},
        ),
        migrations.RemoveField(
            model_name='orders',
            name='category',
        ),
        migrations.AddField(
            model_name='orders',
            name='summa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='phone',
            name='summa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='summa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 12, 21, 4, 41, 613115), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 12, 21, 4, 41, 614623), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 12, 21, 4, 41, 615634), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 12, 21, 4, 41, 614623), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 12, 21, 4, 41, 614623), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
    ]
