# Generated by Django 4.2.6 on 2023-12-12 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_orders_options_alter_shoppingcart_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 12, 21, 9, 55, 658609), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 12, 21, 9, 55, 659609), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 12, 21, 9, 55, 660612), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='summa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 12, 21, 9, 55, 659609), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='summa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 12, 21, 9, 55, 660612), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='summa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Стоимость'),
        ),
    ]
