# Generated by Django 4.2.6 on 2023-12-12 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_blog_posted_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.TextField(default='В обработке', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 12, 21, 48, 38, 380431), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 12, 21, 48, 38, 380431), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 12, 21, 48, 38, 381430), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 12, 21, 48, 38, 381430), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 12, 21, 48, 38, 381430), verbose_name='Опубликована'),
        ),
    ]
